#SPIRIT LEVELING CALCULAOR 
# TALE NOTICE THAT CODE THAT DO CALCULATIONS FOR TASKS INCLUDING CHANGE OF INSTRUMENT STATION 
# THEREFORE I IMPLORE YOU TO DO MANUAL COMPUTATION FOR THE CHANGE POINT EVERYTIME
# I'LL LATER UPGRADE THE CODE TO INCLUDE CHANGE OF STATION POINT



def leveling_calculator():
# BS REFERES TO THE BACK SIGHT READING 
    BS = float(input("INPUT YOUR BACK SIGHT READING : "))

S# RL_BENCHMARK REFERS TO THE REDUCED LEVEL OF THE BENCHMARK WITH RESPECT TO MEAN SEA LEVEL 
    RL_BENCHMARK = float(input("INPUT THE REDUCED LEVEL OF BENCHMARK : "))

#THIS LINE REPRESENTS THE HEIGHT OF THE INSTRUMENT WITH RESPECT TO MEAN SEA LEVEL
    INS_HEIGHT = BS + RL_BENCHMARK

#POINTS REFERS TO THE NUMBER OF INDIVIDUAL READINGS TAKEN 
    points = int(input("ENTER THE TOTAL NUMBER OF INTRUMENT READINGS TAKEN : "))
    
# THESE LINES OF CODE DOES THE REDUCTION OF THE INDIVIDUAL POINT 
    for i in range(1 , points + 1):

        FS = float(input("ENTER YOUR FORE SIGHT READING: "))
        REDUCED_LEVEL = INS_HEIGHT - FS
        print(F"REDUCED LEVEL OF POINT {i} IS {REDUCED_LEVEL} m" )

#LINE TO SHOW THE CALCULATION DONE
    print("LEVELING COMPUTATION COMPLETE")



#FINALLY CODE TO CALL THE FUNCTION TO WORK
leveling_calculator()


