#THIS IS A SIMPLE TRIGONOMETRIC LEVELING CALCULATOR
#THIS DEALS WITH TOTAL STATION , AS YOU'LL NEED THE SLOPE DISTANCE ,VCR

# TAKE NOLTICE THAT WHENEVER THE INSTRUMENT IS SET UP AGAIN OR AFRESH YOU MUST RESTART THE CODE 
#MEANING YOU HAVE TO INPUT THE BACKSIGHT AND EVERYTHING LIKE YOUR FIRST TIME
import math


def tric_calc():
    BS = float(input("ENTER THE BACK SIGHT READING: "))

    RLA = float(input("ENTER THE HEIGHT OF THE CONTROL POINT: "))
  
    
    HI = BS + RLA 

    points = int(input("ENTER THE TOTAL NUMBER OF INTRUMENT READINGS TAKEN : "))



    for i in range(1 , points + 1):

        OBH = float(input("ENTER THE FORESIGHT READING: "))
        VCR = float(input("ENTER THE VERTICAL CIRCLE READING: "))
        SD = float(input("ENTER THE SLOPE DISTANCE : "))
        RL_Unknown = RLA + HI + SD * math.cos(VCR) - OBH
       
        print(f"REDUCED LEVEL OF POINT {i} IS {RL_Unknown} m" )

#LINE TO SHOW THE CALCULATION DONE
    print("LEVELING COMPUTATION COMPLETE")



#FINALLY CODE TO CALL THE FUNCTION TO WORK
tric_calc()





